# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from coastalpayapi.api_helper import APIHelper


class ESignatureControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(ESignatureControllerTests, cls).setUpClass()
        cls.controller = cls.client.e_signature
        cls.response_catcher = cls.controller.http_call_back

    # Get a list of available applications
    def test_get_a_list_of_available_applications(self):

        # Perform the API call through the SDK function
        result = self.controller.get_a_list_of_available_applications()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))


