# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ActiveEnum(object):

    """Implementation of the 'Active' enum.

    Active tab

    Attributes:
        ENUM_0: TODO: type description here.
        ENUM_1: TODO: type description here.

    """

    ENUM_0 = 0

    ENUM_1 = 1
