# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AlignmentEnum(object):

    """Implementation of the 'Alignment' enum.

    Field alignment

    Attributes:
        LEFT: TODO: type description here.
        MIDDLE: TODO: type description here.
        RIGHT: TODO: type description here.
        LEFT_COLUMN: TODO: type description here.
        RIGHT_COLUMN: TODO: type description here.
        FLOAT_LEFT_WHOLE_ROW: TODO: type description here.
        FLOAT_LEFT: TODO: type description here.
        FLOAT_MIDDLE: TODO: type description here.

    """

    LEFT = 'left'

    MIDDLE = 'middle'

    RIGHT = 'right'

    LEFT_COLUMN = 'left_column'

    RIGHT_COLUMN = 'right_column'

    FLOAT_LEFT_WHOLE_ROW = 'float_left_whole_row'

    FLOAT_LEFT = 'float_left'

    FLOAT_MIDDLE = 'float_middle'
