# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClassEnum(object):

    """Implementation of the 'Class' enum.

    Tab class

    Attributes:
        ENUM_  EMPTY STRING FOR TAB: TODO: type description here.
        SET: TODO: type description here.
        DOCUMENTS: TODO: type description here.
        ALTDOCS: TODO: type description here.
        NOTES: TODO: type description here.

    """

    ENUM__EMPTY_STRING_FOR_TAB = '\' - empty string for TAB'

    SET = 'set'

    DOCUMENTS = 'documents'

    ALTDOCS = 'altdocs'

    NOTES = 'notes'
