# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DateFilter1Enum(object):

    """Implementation of the 'date_filter1' enum.

    TODO: type enum description here.

    Attributes:
        DATE: TODO: type description here.
        SET_AT: TODO: type description here.
        MODIFIED: TODO: type description here.
        CONFIRMED: TODO: type description here.
        RESCHEDULED: TODO: type description here.
        SEEN: TODO: type description here.

    """

    DATE = 'date'

    SET_AT = 'set_at'

    MODIFIED = 'modified'

    CONFIRMED = 'confirmed'

    RESCHEDULED = 'rescheduled'

    SEEN = 'seen'
