# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DateFilterEnum(object):

    """Implementation of the 'date_filter' enum.

    TODO: type enum description here.

    Attributes:
        CREATED: TODO: type description here.
        MODIFIED: TODO: type description here.
        LAST_NOTE: TODO: type description here.
        LAST_STATUS: TODO: type description here.
        LAST_TASK: TODO: type description here.
        LAST_TASK_DUE: TODO: type description here.
        LAST_APPOINTMENT: TODO: type description here.
        LAST_APPOINTMENT_DUE: TODO: type description here.

    """

    CREATED = 'created'

    MODIFIED = 'modified'

    LAST_NOTE = 'last_note'

    LAST_STATUS = 'last_status'

    LAST_TASK = 'last_task'

    LAST_TASK_DUE = 'last_task_due'

    LAST_APPOINTMENT = 'last_appointment'

    LAST_APPOINTMENT_DUE = 'last_appointment_due'
