# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coastalpayapi.api_helper import APIHelper
import os
from coastalpayapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError


class DuplicateActivity(object):

    """Implementation of the 'DuplicateActivity' model.

    TODO: type model description here.

    Attributes:
        id (int): Activity Id
        old_lead_id (int): Old lead Id
        new_lead_id (int): New lead Id
        duplicated_by (int): User Id
        duplicated_at (datetime): Date of duplication (Y-m-d\TH:i:sP)

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "old_lead_id": 'oldLeadId',
        "new_lead_id": 'newLeadId',
        "duplicated_by": 'duplicatedBy',
        "duplicated_at": 'duplicatedAt'
    }

    _optionals = [
        'id',
        'old_lead_id',
        'new_lead_id',
        'duplicated_by',
        'duplicated_at',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 old_lead_id=APIHelper.SKIP,
                 new_lead_id=APIHelper.SKIP,
                 duplicated_by=APIHelper.SKIP,
                 duplicated_at=APIHelper.SKIP):
        """Constructor for the DuplicateActivity class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if old_lead_id is not APIHelper.SKIP:
            self.old_lead_id = old_lead_id 
        if new_lead_id is not APIHelper.SKIP:
            self.new_lead_id = new_lead_id 
        if duplicated_by is not APIHelper.SKIP:
            self.duplicated_by = duplicated_by 
        if duplicated_at is not APIHelper.SKIP:
            self.duplicated_at = APIHelper.RFC3339DateTime(duplicated_at) if duplicated_at else None 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        old_lead_id = dictionary.get("oldLeadId") if dictionary.get("oldLeadId") else APIHelper.SKIP
        new_lead_id = dictionary.get("newLeadId") if dictionary.get("newLeadId") else APIHelper.SKIP
        duplicated_by = dictionary.get("duplicatedBy") if dictionary.get("duplicatedBy") else APIHelper.SKIP
        duplicated_at = APIHelper.RFC3339DateTime.from_value(dictionary.get("duplicatedAt")).datetime if dictionary.get("duplicatedAt") else APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   old_lead_id,
                   new_lead_id,
                   duplicated_by,
                   duplicated_at)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        file_name = os.path.basename(__file__).removesuffix(".py")
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__), file_name)).is_valid(val)
