# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FieldTypeEnum(object):

    """Implementation of the 'FieldType' enum.

    Field type

    Attributes:
        TEXT: TODO: type description here.
        CHECKBOX: TODO: type description here.

    """

    TEXT = 'Text'

    CHECKBOX = 'Checkbox'
