# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coastalpayapi.api_helper import APIHelper
import os
from coastalpayapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError


class FileLabel(object):

    """Implementation of the 'FileLabel' model.

    TODO: type model description here.

    Attributes:
        id (int): Label Id
        order (int): Label display order
        name (string): Label name

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "order": 'order',
        "name": 'name'
    }

    _optionals = [
        'id',
        'order',
        'name',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 order=APIHelper.SKIP,
                 name=APIHelper.SKIP):
        """Constructor for the FileLabel class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if order is not APIHelper.SKIP:
            self.order = order 
        if name is not APIHelper.SKIP:
            self.name = name 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        order = dictionary.get("order") if dictionary.get("order") else APIHelper.SKIP
        name = dictionary.get("name") if dictionary.get("name") else APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   order,
                   name)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        file_name = os.path.basename(__file__).removesuffix(".py")
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__), file_name)).is_valid(val)
