# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coastalpayapi.api_helper import APIHelper
import os
from coastalpayapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError


class LeadFieldValue(object):

    """Implementation of the 'LeadFieldValue' model.

    TODO: type model description here.

    Attributes:
        uid (int): Field unique Id
        id (string): Field Id
        field (string): Field name
        value (string): Field value

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uid": 'uid',
        "id": 'id',
        "field": 'field',
        "value": 'value'
    }

    _optionals = [
        'uid',
        'id',
        'field',
        'value',
    ]

    def __init__(self,
                 uid=APIHelper.SKIP,
                 id=APIHelper.SKIP,
                 field=APIHelper.SKIP,
                 value=APIHelper.SKIP):
        """Constructor for the LeadFieldValue class"""

        # Initialize members of the class
        if uid is not APIHelper.SKIP:
            self.uid = uid 
        if id is not APIHelper.SKIP:
            self.id = id 
        if field is not APIHelper.SKIP:
            self.field = field 
        if value is not APIHelper.SKIP:
            self.value = value 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        uid = dictionary.get("uid") if dictionary.get("uid") else APIHelper.SKIP
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        field = dictionary.get("field") if dictionary.get("field") else APIHelper.SKIP
        value = dictionary.get("value") if dictionary.get("value") else APIHelper.SKIP
        # Return an object of this model
        return cls(uid,
                   id,
                   field,
                   value)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        file_name = os.path.basename(__file__).removesuffix(".py")
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__), file_name)).is_valid(val)
