# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coastalpayapi.api_helper import APIHelper
import os
from coastalpayapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError


class LeadFieldOrder(object):

    """Implementation of the 'LeadFieldOrder' model.

    TODO: type model description here.

    Attributes:
        value (int): New order position of lead field
        mtype (Type1Enum): Type of changing order position

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "value": 'value',
        "mtype": 'type'
    }

    _optionals = [
        'mtype',
    ]

    def __init__(self,
                 value=None,
                 mtype='null'):
        """Constructor for the LeadFieldOrder class"""

        # Initialize members of the class
        self.value = value 
        self.mtype = mtype 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        value = dictionary.get("value") if dictionary.get("value") else None
        mtype = dictionary.get("type") if dictionary.get("type") else 'null'
        # Return an object of this model
        return cls(value,
                   mtype)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        file_name = os.path.basename(__file__).removesuffix(".py")
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__), file_name)).is_valid(val)
