# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coastalpayapi.api_helper import APIHelper
from coastalpayapi.models.brief_lead_info import BriefLeadInfo
from coastalpayapi.models.detail import Detail
import os
from coastalpayapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError


class LeadsResponse2(object):

    """Implementation of the 'Leads Response2' model.

    TODO: type model description here.

    Attributes:
        general (BriefLeadInfo): TODO: type description here.
        details (list of Detail): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "general": 'general',
        "details": 'details'
    }

    _optionals = [
        'general',
        'details',
    ]

    def __init__(self,
                 general=APIHelper.SKIP,
                 details=APIHelper.SKIP):
        """Constructor for the LeadsResponse2 class"""

        # Initialize members of the class
        if general is not APIHelper.SKIP:
            self.general = general 
        if details is not APIHelper.SKIP:
            self.details = details 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        general = BriefLeadInfo.from_dictionary(dictionary.get('general')) if 'general' in dictionary.keys() else APIHelper.SKIP 
        details = None
        if dictionary.get('details') is not None:
            details = [Detail.from_dictionary(x) for x in dictionary.get('details')]
        else:
            details = APIHelper.SKIP
        # Return an object of this model
        return cls(general,
                   details)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        file_name = os.path.basename(__file__).removesuffix(".py")
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__), file_name)).is_valid(val)
