# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coastalpayapi.api_helper import APIHelper
from coastalpayapi.models.links import Links
from coastalpayapi.models.links_activity import LinksActivity
from coastalpayapi.models.meta import Meta
import os
from coastalpayapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError


class LeadsActivityLinksResponse(object):

    """Implementation of the 'Leads Activity Links Response' model.

    TODO: type model description here.

    Attributes:
        data (list of LinksActivity): TODO: type description here.
        links (Links): TODO: type description here.
        meta (Meta): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "data": 'data',
        "links": 'links',
        "meta": 'meta'
    }

    _optionals = [
        'data',
        'links',
        'meta',
    ]

    def __init__(self,
                 data=APIHelper.SKIP,
                 links=APIHelper.SKIP,
                 meta=APIHelper.SKIP):
        """Constructor for the LeadsActivityLinksResponse class"""

        # Initialize members of the class
        if data is not APIHelper.SKIP:
            self.data = data 
        if links is not APIHelper.SKIP:
            self.links = links 
        if meta is not APIHelper.SKIP:
            self.meta = meta 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        data = None
        if dictionary.get('data') is not None:
            data = [LinksActivity.from_dictionary(x) for x in dictionary.get('data')]
        else:
            data = APIHelper.SKIP
        links = Links.from_dictionary(dictionary.get('links')) if 'links' in dictionary.keys() else APIHelper.SKIP 
        meta = Meta.from_dictionary(dictionary.get('meta')) if 'meta' in dictionary.keys() else APIHelper.SKIP 
        # Return an object of this model
        return cls(data,
                   links,
                   meta)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        file_name = os.path.basename(__file__).removesuffix(".py")
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__), file_name)).is_valid(val)
