# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coastalpayapi.api_helper import APIHelper
import os
from coastalpayapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError


class LeadsFieldsOrderResponse(object):

    """Implementation of the 'Leads Fields Order Response' model.

    TODO: type model description here.

    Attributes:
        result (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "result": 'result'
    }

    _optionals = [
        'result',
    ]

    def __init__(self,
                 result=APIHelper.SKIP):
        """Constructor for the LeadsFieldsOrderResponse class"""

        # Initialize members of the class
        if result is not APIHelper.SKIP:
            self.result = result 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        result = dictionary.get("result") if dictionary.get("result") else APIHelper.SKIP
        # Return an object of this model
        return cls(result)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        file_name = os.path.basename(__file__).removesuffix(".py")
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__), file_name)).is_valid(val)
