# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coastalpayapi.api_helper import APIHelper
import os
from coastalpayapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError


class LeadsUsersRequest1(object):

    """Implementation of the 'Leads Users Request1' model.

    TODO: type model description here.

    Attributes:
        email (string): User Email
        assign_manager (bool): Assign User's Manager

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "email": 'email',
        "assign_manager": 'assign_manager'
    }

    _optionals = [
        'assign_manager',
    ]

    def __init__(self,
                 email=None,
                 assign_manager=APIHelper.SKIP):
        """Constructor for the LeadsUsersRequest1 class"""

        # Initialize members of the class
        self.email = email 
        if assign_manager is not APIHelper.SKIP:
            self.assign_manager = assign_manager 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        email = dictionary.get("email") if dictionary.get("email") else None
        assign_manager = dictionary.get("assign_manager") if "assign_manager" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(email,
                   assign_manager)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        file_name = os.path.basename(__file__).removesuffix(".py")
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__), file_name)).is_valid(val)
