# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coastalpayapi.api_helper import APIHelper
import os
from coastalpayapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError


class Links(object):

    """Implementation of the 'Links' model.

    TODO: type model description here.

    Attributes:
        first (string): An URL to the first page of the data set
        last (string): An URL to the last page of the data set
        prev (string): An URL to the previous page of the data set
        next (string): An URL to the next page of the data set

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "first": 'first',
        "last": 'last',
        "prev": 'prev',
        "next": 'next'
    }

    _optionals = [
        'first',
        'last',
        'prev',
        'next',
    ]

    def __init__(self,
                 first=APIHelper.SKIP,
                 last=APIHelper.SKIP,
                 prev=APIHelper.SKIP,
                 next=APIHelper.SKIP):
        """Constructor for the Links class"""

        # Initialize members of the class
        if first is not APIHelper.SKIP:
            self.first = first 
        if last is not APIHelper.SKIP:
            self.last = last 
        if prev is not APIHelper.SKIP:
            self.prev = prev 
        if next is not APIHelper.SKIP:
            self.next = next 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        first = dictionary.get("first") if dictionary.get("first") else APIHelper.SKIP
        last = dictionary.get("last") if dictionary.get("last") else APIHelper.SKIP
        prev = dictionary.get("prev") if dictionary.get("prev") else APIHelper.SKIP
        next = dictionary.get("next") if dictionary.get("next") else APIHelper.SKIP
        # Return an object of this model
        return cls(first,
                   last,
                   prev,
                   next)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        file_name = os.path.basename(__file__).removesuffix(".py")
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__), file_name)).is_valid(val)
