# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MaskEnum(object):

    """Implementation of the 'Mask' enum.

    Field mask

    Attributes:
        VALIDATESSN: TODO: type description here.
        VALIDATEDATE: TODO: type description here.
        VALIDATEDATE2: TODO: type description here.
        VALIDATEZIP5: TODO: type description here.
        VALIDATEZIP9: TODO: type description here.

    """

    VALIDATESSN = 'validateSSN'

    VALIDATEDATE = 'validateDate'

    VALIDATEDATE2 = 'validateDate2'

    VALIDATEZIP5 = 'validateZip5'

    VALIDATEZIP9 = 'validateZip9'
