# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PerPage3Enum(object):

    """Implementation of the 'per_page3' enum.

    TODO: type enum description here.

    Attributes:
        ENUM_10: TODO: type description here.
        ENUM_25: TODO: type description here.
        ENUM_50: TODO: type description here.
        ENUM_100: TODO: type description here.

    """

    ENUM_10 = 10

    ENUM_25 = 25

    ENUM_50 = 50

    ENUM_100 = 100
