# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PriorityEnum(object):

    """Implementation of the 'Priority' enum.

    Priority

    Attributes:
        NORMAL: TODO: type description here.
        MEDIUM: TODO: type description here.
        HIGH: TODO: type description here.

    """

    NORMAL = 'Normal'

    MEDIUM = 'Medium'

    HIGH = 'High'
