# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SortByEnum(object):

    """Implementation of the 'sort_by' enum.

    TODO: type enum description here.

    Attributes:
        ID: TODO: type description here.
        MID: TODO: type description here.
        NAME: TODO: type description here.
        CREATED: TODO: type description here.
        MODIFIED: TODO: type description here.

    """

    ID = 'id'

    MID = 'mid'

    NAME = 'name'

    CREATED = 'created'

    MODIFIED = 'modified'
