# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SortDirEnum(object):

    """Implementation of the 'sort_dir' enum.

    TODO: type enum description here.

    Attributes:
        ASC: TODO: type description here.
        DESC: TODO: type description here.

    """

    ASC = 'asc'

    DESC = 'desc'
