# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SortBy1Enum(object):

    """Implementation of the 'sort_by1' enum.

    TODO: type enum description here.

    Attributes:
        ID: TODO: type description here.
        SET_FOR: TODO: type description here.
        SET_AT: TODO: type description here.
        SET_BY: TODO: type description here.
        MODIFIED: TODO: type description here.
        MODIFIED_BY: TODO: type description here.
        DATE: TODO: type description here.
        DATE_END: TODO: type description here.
        CONFIRMED: TODO: type description here.
        CONFIRMED_BY: TODO: type description here.
        SEEN: TODO: type description here.
        SEEN_BY: TODO: type description here.
        RESCHEDULED: TODO: type description here.
        RESCHEDULED_BY: TODO: type description here.

    """

    ID = 'id'

    SET_FOR = 'set_for'

    SET_AT = 'set_at'

    SET_BY = 'set_by'

    MODIFIED = 'modified'

    MODIFIED_BY = 'modified_by'

    DATE = 'date'

    DATE_END = 'date_end'

    CONFIRMED = 'confirmed'

    CONFIRMED_BY = 'confirmed_by'

    SEEN = 'seen'

    SEEN_BY = 'seen_by'

    RESCHEDULED = 'rescheduled'

    RESCHEDULED_BY = 'rescheduled_by'
