# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SpecialEnum(object):

    """Implementation of the 'Special' enum.

    Field special value

    Attributes:
        MID: TODO: type description here.
        DBA: TODO: type description here.
        SALES_NUMBER: TODO: type description here.
        BUSADDRESS: TODO: type description here.
        BUSCITY: TODO: type description here.
        BUSSTATE: TODO: type description here.
        BUSZIPCODE: TODO: type description here.
        BUSTYPE: TODO: type description here.
        BUSPRODUCTS: TODO: type description here.
        BUSMARKETTYPE: TODO: type description here.
        BUSSTARTDATE: TODO: type description here.
        SIC: TODO: type description here.
        TAXID: TODO: type description here.
        PROCESSOR: TODO: type description here.
        OWNER_FNAME: TODO: type description here.
        OWNER_LNAME: TODO: type description here.
        OWNER_TITLE: TODO: type description here.
        OWNER_SSN: TODO: type description here.
        PHONE: TODO: type description here.
        CELLPHONE: TODO: type description here.
        EMAIL: TODO: type description here.
        CONTACT: TODO: type description here.
        CONTACT_1: TODO: type description here.
        CONTACT_2: TODO: type description here.
        AVGTCKT: TODO: type description here.
        VOLUME: TODO: type description here.
        BANK_NAME_ON_ACCOUNT: TODO: type description here.
        BANK_ACCOUNT_TYPE: TODO: type description here.
        BANK_ACCOUNT_OWNER_TYPE: TODO: type description here.
        ABA_CODE: TODO: type description here.
        ACCOUNT_NUMBER: TODO: type description here.
        BANK_NAME: TODO: type description here.
        BANK_CITY: TODO: type description here.
        BANK_STATE: TODO: type description here.
        BANK_ZIP: TODO: type description here.
        LMS_FSCORE: TODO: type description here.
        LMS_REFNUM: TODO: type description here.
        LR_MONTHLY_PAYMENT: TODO: type description here.
        LR_EQUIPMENT: TODO: type description here.
        LR_WIRE_TRANFER: TODO: type description here.
        LR_PACK_FEE: TODO: type description here.
        LR_CANCELLATION: TODO: type description here.
        LEADID: TODO: type description here.

    """

    MID = 'mid'

    DBA = 'dba'

    SALES_NUMBER = 'sales_number'

    BUSADDRESS = 'busaddress'

    BUSCITY = 'buscity'

    BUSSTATE = 'busstate'

    BUSZIPCODE = 'buszipcode'

    BUSTYPE = 'bustype'

    BUSPRODUCTS = 'busproducts'

    BUSMARKETTYPE = 'busmarkettype'

    BUSSTARTDATE = 'busstartdate'

    SIC = 'sic'

    TAXID = 'taxid'

    PROCESSOR = 'processor'

    OWNER_FNAME = 'owner_fname'

    OWNER_LNAME = 'owner_lname'

    OWNER_TITLE = 'owner_title'

    OWNER_SSN = 'owner_ssn'

    PHONE = 'phone'

    CELLPHONE = 'cellphone'

    EMAIL = 'email'

    CONTACT = 'contact'

    CONTACT_1 = 'contact_1'

    CONTACT_2 = 'contact_2'

    AVGTCKT = 'avgtckt'

    VOLUME = 'volume'

    BANK_NAME_ON_ACCOUNT = 'bank_name_on_account'

    BANK_ACCOUNT_TYPE = 'bank_account_type'

    BANK_ACCOUNT_OWNER_TYPE = 'bank_account_owner_type'

    ABA_CODE = 'aba_code'

    ACCOUNT_NUMBER = 'account_number'

    BANK_NAME = 'bank_name'

    BANK_CITY = 'bank_city'

    BANK_STATE = 'bank_state'

    BANK_ZIP = 'bank_zip'

    LMS_FSCORE = 'LMS_FScore'

    LMS_REFNUM = 'LMS_RefNum'

    LR_MONTHLY_PAYMENT = 'LR_MONTHLY_PAYMENT'

    LR_EQUIPMENT = 'LR_EQUIPMENT'

    LR_WIRE_TRANFER = 'LR_WIRE_TRANFER'

    LR_PACK_FEE = 'LR_PACK_FEE'

    LR_CANCELLATION = 'LR_CANCELLATION'

    LEADID = 'leadID'
