# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Special1Enum(object):

    """Implementation of the 'Special1' enum.

    Special type of mapped field

    Attributes:
        NULL: TODO: type description here.
        CHK: TODO: type description here.
        D2T: TODO: type description here.
        SALESREP: TODO: type description here.
        SALESREP_POSITION: TODO: type description here.
        SALESREP_EMAIL: TODO: type description here.
        SALESREP_PHONE: TODO: type description here.
        SALESREP_MOBILE: TODO: type description here.
        SALESREP_FAX: TODO: type description here.
        SALESREP_EXT: TODO: type description here.
        LEADING_COMMA: TODO: type description here.
        DATE_MDY: TODO: type description here.
        DATE_MDY1: TODO: type description here.

    """

    NULL = 'null'

    CHK = 'chk'

    D2T = 'd2t'

    SALESREP = 'salesrep'

    SALESREP_POSITION = 'salesrep_position'

    SALESREP_EMAIL = 'salesrep_email'

    SALESREP_PHONE = 'salesrep_phone'

    SALESREP_MOBILE = 'salesrep_mobile'

    SALESREP_FAX = 'salesrep_fax'

    SALESREP_EXT = 'salesrep_ext'

    LEADING_COMMA = 'leading_comma'

    DATE_MDY = 'date_mdY'

    DATE_MDY1 = 'date_mdy'
