# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusEnum(object):

    """Implementation of the 'Status' enum.

    Status of link

    Attributes:
        LINKED: TODO: type description here.
        UNLINKED: TODO: type description here.

    """

    LINKED = 'Linked'

    UNLINKED = 'Unlinked'
