# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StickyEnum(object):

    """Implementation of the 'Sticky' enum.

    Pin to top?

    Attributes:
        YES: TODO: type description here.
        NO: TODO: type description here.

    """

    YES = 'Yes'

    NO = 'No'
