# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Sticky1Enum(object):

    """Implementation of the 'Sticky1' enum.

    Pin note to top

    Attributes:
        YES: TODO: type description here.
        NO: TODO: type description here.

    """

    YES = 'Yes'

    NO = 'No'
