# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TypeEnum(object):

    """Implementation of the 'Type' enum.

    Field type

    Attributes:
        DATECREATE: TODO: type description here.
        GOOGLEMAPS: TODO: type description here.
        JQDATE: TODO: type description here.
        NUMBER: TODO: type description here.
        TXT: TODO: type description here.
        TXTAREA: TODO: type description here.
        TXTDOLLAR: TODO: type description here.
        TXTBALANCE: TODO: type description here.
        TXTSIC: TODO: type description here.
        TXTPERCENT: TODO: type description here.
        TXTROUTING: TODO: type description here.
        TXTSECURE: TODO: type description here.
        TXTMASKED: TODO: type description here.
        CHECKBOX: TODO: type description here.
        SELECT: TODO: type description here.
        SELECTRED: TODO: type description here.
        LABEL: TODO: type description here.
        PACKAGES: TODO: type description here.
        PHONEMASK: TODO: type description here.
        PRFORMATS: TODO: type description here.
        QUICKEMAIL: TODO: type description here.
        QUICKFAX: TODO: type description here.
        TIMEZONE: TODO: type description here.

    """

    DATECREATE = 'DateCreate'

    GOOGLEMAPS = 'GoogleMaps'

    JQDATE = 'jQDate'

    NUMBER = 'Number'

    TXT = 'Txt'

    TXTAREA = 'TxtArea'

    TXTDOLLAR = 'TxtDollar'

    TXTBALANCE = 'TxtBalance'

    TXTSIC = 'TxtSIC'

    TXTPERCENT = 'TxtPercent'

    TXTROUTING = 'TxtRouting'

    TXTSECURE = 'TxtSecure'

    TXTMASKED = 'TxtMasked'

    CHECKBOX = 'Checkbox'

    SELECT = 'Select'

    SELECTRED = 'SelectRed'

    LABEL = 'Label'

    PACKAGES = 'Packages'

    PHONEMASK = 'PhoneMask'

    PRFORMATS = 'PrFormats'

    QUICKEMAIL = 'QuickEmail'

    QUICKFAX = 'QuickFax'

    TIMEZONE = 'TimeZone'
