# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type2Enum(object):

    """Implementation of the 'Type2' enum.

    TODO: type enum description here.

    Attributes:
        TAB: TODO: type description here.
        SET: TODO: type description here.

    """

    TAB = 'tab'

    SET = 'set'
