# -*- coding: utf-8 -*-

"""
coastalpayapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type1Enum(object):

    """Implementation of the 'Type1' enum.

    Type of changing order position

    Attributes:
        INCREMENT: TODO: type description here.
        DECREMENT: TODO: type description here.
        NULL: TODO: type description here.

    """

    INCREMENT = 'increment'

    DECREMENT = 'decrement'

    NULL = 'null'
